# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: gateway.telekom.de/v1alpha1
kind: GatewayCredential
metadata:
  name: example-credential-jwt
  namespace: gateway-core
spec:
  type: jwt
  issuer: https://stargate-integration.test.dhei.telekom.de/auth/realms/default
  jwksUri: https://stargate-integration.test.dhei.telekom.de/auth/realms/default/protocol/openid-connect/certs
  scopes:
    - orders:read
    - orders:write
