{{/*
SPDX-FileCopyrightText: 2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}
{{- $np := index .Values "network-policy" -}}
{{- if $np.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "data-plane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-plane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "data-plane.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if $np.ingress }}
    - Ingress
    {{- end }}
    {{- if $np.egress }}
    - Egress
    {{- end }}
  {{- with $np.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $np.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
