{{/*
SPDX-FileCopyrightText: 2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-plane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-plane.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "data-plane.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.ports.proxy }}
      targetPort: proxy
      protocol: TCP
    - name: management
      port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
